{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "deploy-service.serviceAccountName" . }}
  namespace: {{ include "deploy-service.namespace" . }}
  labels:
    {{- include "deploy-service.labels" . | nindent 4 }}
  {{- with merge (deepCopy (.Values.serviceAccount.annotations | default dict)) (deepCopy (.Values.commonAnnotations | default dict)) }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
{{- end }}
